version: "3.9"

networks:
  pcbtags:

services:
  pcbtags-server:
    image: thestaticturtle/pcbtags-server
    networks:
      - pcbtags
    depends_on:
      - pcbtags-cache

  pcbtags-frontend:
    image: thestaticturtle/pcbtags-frontend
    networks:
      - pcbtags

  pcbtags-gateway:
    image: nginx:1.19-alpine
    ports:
      - "9000:80"
    volumes:
      - ./gateway.ngnix.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pcbtags
    depends_on:
      - pcbtags-frontend
      - pcbtags-server

  pcbtags-cache:
    image: "redis:alpine"
    networks:
      - pcbtags
